# Generated by Django 3.2.23 on 2024-02-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('raw', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accredited_it_employer', models.BooleanField()),
                ('trusted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('station_id', models.CharField(max_length=255)),
                ('line_id', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_1', models.IntegerField()),
                ('to', models.IntegerField()),
                ('gross', models.BooleanField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255)),
                ('responsibility', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255, null=True)),
                ('has_test', models.BooleanField()),
                ('response_letter_required', models.BooleanField()),
                ('response_url', models.CharField(max_length=255)),
                ('sort_point_distance', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField()),
                ('show_logo_in_search', models.BooleanField()),
                ('insider_interview', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.address')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.area')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employer')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employment')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.experience')),
                ('professional_roles', models.ManyToManyField(to='mainapp.Professions')),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.salary')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.schedule')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.snippet')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.type')),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='address',
            name='metro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.metro'),
        ),
    ]
